### ISSUE TITLE
Dead Letter error, mailbox.send('TASK') doesn't work properly

### ISSUE THREAD

**Issue by burakakca** [huan/mailbox#10]
```bash
# testing the mailbox-ed(actor) machine ... (an actor will be able to response two events one by one)
> sending event #0
{ type: 'TASK' }
{
  type: 'mailbox/DEAD_LETTER',
  payload: {
    message: { type: 'TASK' },
    data: 'message has no origin (un-repliable)'
  }
}
> sending event #1
{ type: 'TASK' }
{
  type: 'mailbox/DEAD_LETTER',
  payload: {
    message: { type: 'TASK' },
    data: 'message has no origin (un-repliable)'
  }
}
# testing mailbox-ed machine ... done
```

**Comment by huan** [comment]
@burakakca Thanks for the reporting!

The problem is that the Mailbox needs an actor to reply to, but in our code, we just use the `Mailbox.send`, which will lack the sender actor address, which leads to the `DEAD_LETTER` problem.

I will add an actor to the example code as the EVENT sender which I believe will fix this problem.

**Comment by huan** [comment]
I believe the latest code should be able to correct and demonstrate what we want to show up:

```
$ ./examples/mailbox-demo.ts 
(machine)<Mailbox> states.Idle.entry
####################################################################
# testing the raw machine ... (a raw machine will only be able to response the first event)
> sending event #0
TASK_RECEIVED
> sending event #1
# testing raw machine: taskCounter = 1

####################################################################
# testing the mailbox-ed(actor) machine ... (an actor will be able to response two events one by one)
> sending event #0
TASK received by actor
TASK_RECEIVED
> sending event #1
TASK received by actor
TASK_RECEIVED received by actor
TASK_RECEIVED
TASK_RECEIVED received by actor
# testing mailbox-ed machine: taskCounter = 2
```

Please feel free to send a PR if you have any idea to improve it (both code and the docs), thank you very much!

**Comment by burakakca** [comment]
Yes, It works now thanks.

**Comment by huan** [comment]
You are welcome!

Could you please share about what your use case looks like?

I’m using the Mailbox actor for myself a little while, for the distributed state machine as actors, and I also have some plan to improve the remote procedure call about this library.

Would love to learn from you with your experiences!
